
name: Node.js CI

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: 'Configurar clave SSH'
              run: |
                echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
                chmod 400 key.pem
            - name: 'Conectar a EC2 y borrar carpeta'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-3-95-181-149.compute-1.amazonaws.com "rm -rf /downloads/Proyectito"
            - name: 'Clonar repositorio en EC2'
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-3-95-181-149.compute-1.amazonaws.com "git clone https://github.com/KennethTaipe06/Proyectito.git /downloads/Proyectito"
            - name: 'Eliminar clave SSH'
              run: rm key.pem